### ISSUE TITLE
Update worlds list

### ISSUE THREAD

**Issue by mateuseap** [DAndrewBox/Old-Tibia-Name-Generator#1]
I have two ideas that I believe would enhance the feature for appending worlds to the generated names:

1. Ensure the worlds list reflects the current Tibia worlds.
2. Introduce a new option to append either current Tibia worlds or old Tibia worlds to the names.

While the first idea might not align perfectly with the purpose of this website, the second idea could be a valuable feature. If PRs for these enhancements are accepted and the proposed changes make sense, I'd be happy to work on implementing them.

Great work!

**Comment by DAndrewBox** [comment]
PRs are accepted! But I took the time to make the change for this one since it was a small change.
Hopefully is what you wanted, if not, don't hesitate to tell me and if you want open a PR with the change 😃

**Comment by mateuseap** [comment]
@DAndrewBox, I really appreciate your quick response and the effort you've put in! I tested it out and enjoyed it. Thanks for considering this proposal. Again, great work! The simplicity of this project makes it very nice, and I truly enjoyed it 😄
